### ISSUE TITLE
Markdown links

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#602]
It's easy to end up with broken links in markdown, see e.g. commit af87a01

To help with this, I created [check-markdown-links.py](https://github.com/Akuli/porcupine/blob/b6ea2acb9b4786f226dbaec6d234130ffd5788af/scripts/check-markdown-links.py), a simple Python script that validates all links in markdown files. I use it in Porcupine and I think in some other repo too, but I can't remember which one.

We should add it to Jou too. It needs to be edited a little bit for Jou, but probably not much. (The script mentions "porcupine" a couple times.)

Running the script in GitHub actions could be super simple. Something like this in `linux.yml`:

```yml
- uses: actions/setup-python@v5
  with:
    python-version: '3.13' 
- run: pip install requests
- run: python my_script.py
```

This would be pretty easy to contribute. If nobody does this, I'll do it myself eventually :)
