### ISSUE TITLE
Moosems thoughts about what Jou should/shouldn't have

### ISSUE THREAD

**Issue by Akuli** [Akuli/jou#77]
- "a good easy package manager like pip goes a long way"
- "And good stack traces and errors like in python"
- "I dislike the whole importing thing in C/C++ ... for example the header files and source files could just be one"

I agree with all of these points.

**Comment by Moosems** [comment]
Any thoughts on the package manager?

**Comment by Akuli** [comment]
Yes:
- Important, but will not happen any time soon
- As is typical in Jou, make it as simple as possible
- Extracts packages to a project-specific folder named `libs` or something, with a super simple structure: `libs/foo/bar.jou` is file `bar.jou` from package `foo`
- Syntax for importing from a package: `import "libs/foo/bar.jou"`
- No need for Python-style virtualenvs, the `libs` folder "just works"
- Creates two files: what you installed (human-readable) and checksums of downloads (not so human-readable). Both are supposed to be committed to git. This is what  to npm and cargo do, for example.

Package manager usage would look like:

```
$ joupkg install https://example.com/some-package.zip
$ joupkg install Akuli/foo    # install from https://github.com/Akuli/foo
```

The `user/repo` syntax would be actually a shorthand for the second kind of syntax. GitHub supports downloadable zip files.

**Comment by Akuli** [comment]
> Creates two files: what you installed (human-readable) and checksums of downloads (not so human-readable). Both are supposed to be committed to git. This is what to npm and cargo do, for example.

Instead of this, I think there should be just one file, e.g. `joupkg.toml`. It could look like this:

```toml
["libs/joujson"]
git_url = "https://github.com/Akuli/jou"
git_commit = "20f3a30f02dfd5a398aa8dbee04ff9a3b90d9248"
folder_hash = "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03"
subfolder = "packages/joujson"

["libs/foo"]
git_url = "https://github.com/Moosems/jou-foo"
git_tag = "v1.0.4"
folder_hash = "167112362adb3b2041c11f7337437872f9d821e57e8c3edd68d87a1d0babd0f5"

["libs/bar"]
download_url = "https://example.com/bar-3.1.4.zip"
download_hash = "d14f73ffe9efb30f7e7ca5bda314561e07c1e2bb94e2692f9979b2bbe19de341"
subfolder = "bar-3.1.4"
```

I asked AI to explain this file to me, and it guessed the meaning of every field exaclty as I had intended, so this seems good. Here's what the AI said:

### Fields Explanation

1. **`["libs/joujson"]`**:
   - This denotes a specific library/package named `joujson`. The brackets suggest that the entry could be a part of a larger list of libraries.

2. **`git_url`**:
   - This specifies the URL of a Git repository from which the package can be cloned or fetched. It indicates that the library is maintained in a version-controlled manner using Git.

3. **`git_commit`**:
   - This field refers to a specific commit in the Git repository that should be checked out. It provides a snapshot of the code at that point, ensuring that you are using a stable and specific version of the package.

4. **`folder_hash`**:
   - This likely represents a hash (perhaps SHA256 or similar) that uniquely identifies the content of the folder at the specified commit. It could be used for integrity checking, ensuring that the fetched content matches the expected state.

5. **`subfolder`**:
   - This indicates the specific subdirectory within the repository where the relevant package/library code resides. This is particularly useful if the Git repository contains multiple projects or components.

6. **`["libs/foo"]`**:
   - Similar to `joujson`, this is another library named `foo`.

7. **`git_tag`**:
   - This specifies a tagged release in the Git repository, representing a specific version of the package (in this case, "v1.0.4"). Tags are generally used to mark release points in the project history.

8. **`["libs/bar"]`**:
   - This denotes yet another package named `bar`.

9. **`download_url`**:
   - Unlike the previous libraries that are sourced from Git, this field provides a direct URL from which to download the library, typically an archive file (like a ZIP).

10. **`download_hash`**:
    - Similar to `folder_hash`, this is a hash used to verify the integrity of the downloaded file. It ensures that the file hasn't been tampered with or corrupted during download.

11. **`subfolder`**:
    - For the `bar` library, this indicates the subdirectory or folder name that corresponds to the downloaded file structure. This could pertain to how the library is organized once extracted from the ZIP file.
